# -*- coding: utf-8 -*-
"""Prediksi Harga Mobil Bekas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12FavrVvY3DpimUO86c3B43TcVpJK0iOS

# Prediksi Harga Mobil Bekas

Notebook ini membangun model machine learning untuk memprediksi harga mobil bekas berdasarkan atribut kendaraan. Permasalahan ini diselesaikan sebagai kasus regresi karena target yang diprediksi adalah nilai numerik, yaitu `price`.

## 1. Setup dan Load Dataset

Bagian ini digunakan untuk menyiapkan library yang dibutuhkan dan memuat dataset dari Kaggle. Dataset dimuat dalam bentuk dataframe agar dapat dianalisis dan diproses menggunakan pandas.

### 1.1 Instalasi Package
 menginstal package `kagglehub` agar dataset dari Kaggle dapat dimuat langsung ke notebook.
"""

!pip install -q kagglehub[pandas-datasets]

"""### 1.2 Import Library
 mengimpor library yang digunakan untuk manipulasi data, visualisasi, preprocessing, modeling, dan evaluasi. Contohnya `pandas` untuk dataframe, `seaborn` dan `matplotlib` untuk visualisasi, serta `scikit-learn` untuk machine learning.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import kagglehub
from kagglehub import KaggleDatasetAdapter
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

"""### 1.3 Memuat Dataset

memuat file `autos.csv` dari dataset Kaggle ke dalam dataframe `df`. Dataframe inilah yang akan digunakan untuk proses analisis, preprocessing, dan modeling.
"""

df = kagglehub.dataset_load(
    KaggleDatasetAdapter.PANDAS,
    "thedevastator/uncovering-factors-that-affect-used-car-prices",
    "autos.csv",
)

"""#### Interpretasi Output

Jika dataset berhasil dimuat tanpa error, dataframe `df` sudah tersedia dan siap digunakan untuk proses eksplorasi data.

## 2. Data Understanding

Tahap ini digunakan untuk memahami struktur dataset, jumlah data, tipe data, missing value, statistik numerik, dan kemungkinan masalah seperti duplikasi, nilai tidak valid, serta outlier. Informasi ini menjadi dasar sebelum melakukan data preparation.

### 2.1 Pemeriksaan Awal Dataset

Beberapa pemeriksaan awal dilakukan untuk memahami data, seperti melihat contoh baris, jumlah data, tipe data, dan jumlah missing value. Tahap ini membantu menentukan langkah preprocessing yang diperlukan.

#### 2.1.1 Melihat Contoh Data

Kode `df.head()` digunakan untuk menampilkan beberapa baris pertama dataset. Tujuannya adalah memahami bentuk data, nama kolom, dan contoh nilai pada setiap fitur.
"""

df.head()

"""#### Interpretasi Output

Output `df.head()` menampilkan contoh lima baris pertama. Dari output ini, kita dapat melihat struktur kolom, contoh nilai, dan gambaran awal isi dataset.

#### 2.1.2 Melihat Ukuran Dataset

Kode `df.shape` digunakan untuk mengetahui jumlah baris dan kolom pada dataset. Ini berguna untuk memastikan dataset memenuhi syarat jumlah sampel minimum dan memahami skala data.
"""

df.shape

"""#### Interpretasi Output

Output `df.shape` menunjukkan ukuran dataset awal. Dataset memiliki jumlah sampel yang besar sehingga memenuhi syarat minimum data untuk proyek machine learning.

#### 2.1.3 Melihat Informasi Tipe Data

Kode `df.info()` digunakan untuk melihat tipe data setiap kolom, jumlah data non null, dan struktur dataframe. Informasi ini penting untuk menentukan kolom mana yang perlu dikonversi, seperti kolom tanggal.
"""

df.info()

"""#### Interpretasi Output

Output `df.info()` menunjukkan tipe data setiap kolom. Kolom tanggal masih perlu dikonversi menjadi datetime, sedangkan kolom kategorikal dan numerik akan diproses dengan teknik yang berbeda.

#### 2.1.4 Mengecek Missing Value Awal

Kode `df.isnull().sum()` digunakan untuk menghitung jumlah nilai kosong pada setiap kolom. Hasil ini membantu menentukan kolom mana yang perlu ditangani dengan imputasi atau strategi lain.
"""

df.isnull().sum()

"""#### Interpretasi Output

Output missing value awal menunjukkan kolom mana saja yang memiliki nilai kosong sebelum cleaning. Kolom seperti `vehicleType`, `gearbox`, `model`, `fuelType`, dan `notRepairedDamage` memiliki missing value yang perlu ditangani.

### 2.2 Kolom dengan Nilai Hilang (NaN)

### 2.3 Statistik Deskriptif, Duplikasi, dan Harga 0

Statistik deskriptif digunakan untuk melihat nilai minimum, maksimum, rata-rata, dan sebaran data numerik. Tahap ini juga digunakan untuk mengecek duplikasi dan mengidentifikasi data dengan `price = 0` sebelum data tersebut dibersihkan.

#### Interpretasi Output

Output statistik deskriptif memperlihatkan adanya nilai ekstrem, seperti `price` yang sangat tinggi, `yearOfRegistration` yang tidak masuk akal, dan `powerPS` yang terlalu besar. Informasi ini digunakan untuk menentukan strategi cleaning.

#### 2.3.1 Melihat Statistik Deskriptif

Kode `df.describe().T` digunakan untuk melihat ringkasan statistik kolom numerik, seperti nilai minimum, maksimum, rata rata, median, dan kuartil. Dari sini dapat terlihat indikasi outlier seperti harga sangat besar, tahun tidak masuk akal, atau `powerPS` ekstrem.
"""

df.describe().T

"""#### Interpretasi Output

Output duplikasi menunjukkan apakah ada baris yang sama persis. Jika hasilnya 0, berarti tidak ada duplikasi penuh yang perlu dihapus.

#### 2.3.2 Mengecek Duplikasi Data

Kode ini menghitung jumlah baris duplikat. Jika terdapat duplikasi, data perlu dipertimbangkan untuk dibersihkan agar model tidak belajar dari data yang berulang.
"""

df.duplicated().sum()

"""#### Interpretasi Output

Output menampilkan baris-baris yang memiliki `price = 0`. Data seperti ini dianggap tidak valid karena harga mobil bekas seharusnya tidak bernilai 0.

#### 2.3.3 Melihat Data dengan Harga 0

Kode ini menampilkan baris yang memiliki `price = 0`. Tujuannya adalah memastikan bahwa nilai tersebut memang ada dan perlu dibersihkan karena tidak merepresentasikan harga mobil yang valid.
"""

df.loc[(df['price']==0)]

"""#### Interpretasi Output

Output menunjukkan jumlah data setelah baris dengan `price = 0` dihapus. Jumlah baris berkurang karena data harga yang tidak valid tidak digunakan dalam modeling.

## 3. Data Preparation

Tahap ini membersihkan data agar siap digunakan untuk modeling. Beberapa proses yang dilakukan meliputi menghapus harga tidak valid, mengubah kolom tanggal, menangani nilai 0 yang sebenarnya merepresentasikan missing value, menangani outlier, membuat fitur `car_age`, menghapus kolom yang tidak relevan, serta melakukan imputasi setelah train-test split untuk mencegah data leakage.

### 3.1 Menghapus Harga Tidak Valid

Data dengan `price = 0` dihapus karena harga mobil tidak mungkin bernilai 0. Nilai ini dianggap sebagai data tidak valid atau placeholder, sehingga tidak digunakan dalam modeling.

#### Interpretasi Output

Cell konversi datetime biasanya tidak menampilkan output. Jika tidak muncul error, berarti kolom tanggal berhasil dikonversi dan dapat digunakan untuk mengambil informasi tahun.
"""

df = df.loc[(df[["price"]]!=0).all(axis=1)]

df.shape

"""### 3.2 Mengubah Kolom Tanggal Menjadi Datetime

Kolom `dateCrawled`, `dateCreated`, dan `lastSeen` diubah menjadi tipe `datetime` menggunakan `pd.to_datetime()`. Perubahan ini diperlukan agar informasi tanggal dapat diproses, misalnya untuk mengambil tahun dan membuat fitur baru seperti `car_age`.

#### Interpretasi Output

Output menampilkan rentang tanggal dari kolom `dateCrawled`, `dateCreated`, dan `lastSeen`. Rentang tanggal ini membantu memastikan bahwa data berasal dari periode waktu yang konsisten.

#### 3.2.1 Kode Konversi Datetime

 membuat daftar kolom tanggal, lalu mengubah setiap kolom menjadi tipe datetime menggunakan `pd.to_datetime()`. Parameter `errors="coerce"` digunakan agar nilai yang gagal dikonversi menjadi `NaT`, bukan membuat error.
"""

date_cols = [
    "dateCrawled",
    "dateCreated",
    "lastSeen",
]

for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors="coerce")

"""#### Interpretasi Output

Output `max_year` menunjukkan tahun maksimum pada data crawling. Nilai ini digunakan sebagai batas atas agar `yearOfRegistration` tidak melebihi tahun pengambilan data.

#### 3.2.2 Melihat Rentang Tanggal

 menampilkan tanggal minimum dan maksimum dari setiap kolom tanggal. Tujuannya adalah memastikan hasil konversi datetime benar dan mengetahui rentang waktu dataset.
"""

for col in date_cols:
    print(col)
    print(df[col].min())
    print(df[col].max())

"""#### Interpretasi Output

Output statistik `yearOfRegistration` menunjukkan nilai minimum dan maksimum yang tidak realistis. Hal ini menjadi alasan mengapa kolom tahun registrasi perlu difilter.

#### 3.2.3 Menentukan Tahun Maksimum Dataset

 mengambil tahun terbesar dari `dateCrawled`. Nilai ini digunakan sebagai batas atas untuk mengecek apakah `yearOfRegistration` masih masuk akal.
"""

max_year = int(df["dateCrawled"].dt.year.max())
print(max_year)

"""#### Interpretasi Output

Boxplot `yearOfRegistration` menunjukkan adanya nilai ekstrem pada tahun registrasi. Visual ini mendukung keputusan untuk melakukan filtering tahun dengan batas yang lebih masuk akal.

### 3.3 Mengubah Nilai 0 Menjadi NaN

Nilai 0 pada `powerPS` dan `monthOfRegistration` dianggap tidak valid. Tenaga mobil 0 tidak masuk akal, dan bulan registrasi valid hanya 1 sampai 12. Karena itu, nilai 0 diubah menjadi NaN agar dapat ditangani melalui imputasi.
"""

df["powerPS"] = df["powerPS"].replace(0, np.nan)
df["monthOfRegistration"] = df["monthOfRegistration"].replace(0, np.nan)

"""#### Interpretasi Output

Cell ini mengubah nilai 0 menjadi NaN dan biasanya tidak menampilkan output. Perubahan tersebut bisa dilihat pada cell berikutnya saat jumlah missing value dicek ulang.

#### 3.3.1 Mengecek Missing Value Setelah Konversi Nilai 0

Setelah `powerPS` dan `monthOfRegistration` bernilai 0 diubah menjadi NaN, kode ini mengecek ulang jumlah missing value. Hasilnya menunjukkan tambahan NaN yang akan ditangani pada tahap imputasi.
"""

df.isnull().sum()

"""#### Interpretasi Output

Output menunjukkan jumlah missing value setelah nilai 0 pada `powerPS` dan `monthOfRegistration` diubah menjadi NaN. Jumlah NaN bertambah karena nilai 0 yang tidak valid kini dianggap sebagai missing value.

#### 3.3.2 Menampilkan Kolom yang Masih Memiliki NaN

Kode ini menyaring hasil missing value agar hanya kolom dengan jumlah NaN lebih dari 0 yang ditampilkan. Tujuannya agar fokus pada kolom yang memang perlu ditangani.
"""

nan_cols_detailed = df.isnull().sum()
nan_cols_detailed = nan_cols_detailed[nan_cols_detailed > 0]
display(nan_cols_detailed.sort_values(ascending=False))

"""#### Interpretasi Output

Output menampilkan hanya kolom yang masih memiliki NaN. Kolom dengan jumlah NaN terbesar perlu diperhatikan, tetapi tidak langsung dihapus karena akan ditangani dengan imputasi.

### 3.4 Mengambil Kolom Numerik

Kolom numerik dipisahkan untuk memudahkan proses visualisasi distribusi dan outlier. Tahap ini membantu fokus pada fitur numerik `price`, `yearOfRegistration`, `powerPS`, `kilometer`, dan `monthOfRegistration`.
"""

numerical_cols = df.select_dtypes(include=["number"]).columns
numerical_cols.tolist()

"""#### Interpretasi Output

Output menampilkan daftar kolom numerik yang akan dianalisis lebih lanjut. Kolom ini digunakan untuk visualisasi boxplot dan histogram.

### 3.5 Visualisasi Distribusi dan Outlier Numerik

Boxplot digunakan untuk melihat outlier pada kolom numerik, sedangkan histogram digunakan untuk melihat bentuk distribusi data. Visualisasi ini membantu menentukan kolom mana yang perlu dibersihkan lebih lanjut.

#### 3.5.1 Boxplot Seluruh Kolom Numerik

Boxplot digunakan untuk melihat nilai ekstrem pada setiap kolom numerik. Visualisasi ini membantu mengidentifikasi kolom yang memiliki outlier, seperti `price`, `yearOfRegistration`, dan `powerPS`.
"""

num_plots = len(numerical_cols)
num_cols = 3
num_rows = (num_plots + num_cols - 1) // num_cols

plt.figure(figsize=(num_cols * 5, num_rows * 4))

for i, col in enumerate(numerical_cols):
    plt.subplot(num_rows, num_cols, i + 1)
    sns.boxplot(x=df[col])
    plt.title(f"Boxplot of {col}")

plt.tight_layout()
plt.show()

"""#### Interpretasi Output

Boxplot seluruh kolom numerik membantu melihat kolom mana yang memiliki outlier ekstrem. Dari visualisasi ini, `powerPS`, `price`, dan `yearOfRegistration` terlihat perlu perhatian khusus.

#### 3.5.2 Histogram Kolom Numerik

Histogram digunakan untuk melihat bentuk distribusi nilai pada kolom numerik yang penting. Dari histogram, kita bisa melihat apakah data condong ke satu sisi, tersebar merata, atau memiliki konsentrasi nilai tertentu.
"""

plot_cols = [
    "price",
    "yearOfRegistration",
    "powerPS",
    "kilometer",
    "monthOfRegistration",
]

plt.figure(figsize=(15, 10))

for i, col in enumerate(plot_cols):
    plt.subplot(2, 3, i + 1)
    sns.histplot(df[col].dropna(), bins=50, kde=False)
    plt.title(f"Histogram of {col}")

plt.tight_layout()
plt.show()

"""#### Interpretasi Output

Histogram menunjukkan pola distribusi masing-masing kolom numerik penting. Jika distribusi condong ke kanan, berarti sebagian besar data berada pada nilai rendah tetapi ada sebagian kecil nilai yang sangat tinggi.

### 3.6 Menangani Outlier `powerPS` dengan IQR

Boxplot menunjukkan bahwa `powerPS` memiliki outlier ekstrem. Metode IQR digunakan untuk menentukan batas bawah dan batas atas secara numerik. Nilai di luar batas tersebut dihapus, sedangkan NaN tetap dipertahankan untuk diimputasi setelah split data.
"""

Q1 = df["powerPS"].quantile(0.25)
Q3 = df["powerPS"].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print(f"powerPS IQR bounds: {lower:.2f} - {upper:.2f}")

df = df[df["powerPS"].between(lower, upper) | df["powerPS"].isna()]
df.shape

"""#### Interpretasi Output

Output menampilkan batas bawah dan batas atas IQR untuk `powerPS`, lalu jumlah data setelah outlier difilter. Nilai `powerPS` di luar batas dianggap terlalu ekstrem dan dihapus, sedangkan NaN tetap dipertahankan.

### 3.7 Feature Engineering: Membuat `car_age`

Fitur `car_age` dibuat dari selisih antara tahun iklan dibuat dan tahun registrasi kendaraan. Umur mobil penting karena kendaraan yang lebih tua umumnya memiliki harga lebih rendah.
"""

df["car_age"] = df["dateCreated"].dt.year - df["yearOfRegistration"]

"""#### Interpretasi Output

Cell ini membuat fitur baru `car_age`. Biasanya tidak ada output tabel, tetapi fitur baru tersebut akan digunakan pada proses filtering dan modeling.

### 3.8 Filtering Tahun Registrasi dan Harga

Data difilter agar tahun registrasi berada pada rentang yang masuk akal, umur mobil tidak negatif, dan harga tidak berada pada nilai ekstrem. Filtering ini membantu mengurangi pengaruh data tidak valid terhadap model.
"""

df = df[
    (df["yearOfRegistration"] >= 1990) &
    (df["yearOfRegistration"] <= max_year) &
    (df["car_age"] >= 0)
]

price_upper = df["price"].quantile(0.99)
df = df[(df["price"] >= 100) & (df["price"] <= price_upper)]

print(f"Shape after outlier filtering: {df.shape}")
df["car_age"].describe()

"""#### Interpretasi Output

Output menunjukkan jumlah data setelah filtering outlier serta statistik `car_age`. Nilai maksimum `car_age` sebesar 26 berarti mobil tertua setelah cleaning berumur 26 tahun, bukan tahun 26.

### 3.9 Menghapus Kolom yang Tidak Digunakan

Beberapa kolom dihapus karena tidak relevan untuk modeling atau informasinya sudah diwakili oleh fitur lain. Contohnya, kolom tanggal dihapus setelah digunakan untuk membuat `car_age`, sedangkan `nrOfPictures` dihapus karena tidak informatif.
"""

drop_cols = [
    "index",
    "nrOfPictures",
    "seller",
    "offerType",
    "name",
    "dateCrawled",
    "dateCreated",
    "lastSeen",
    "abtest",
    "postalCode",
]

df = df.drop(columns=drop_cols)
print(f"Shape after dropping columns: {df.shape}")
df.head()

"""#### Interpretasi Output

Output menampilkan bentuk dataset setelah kolom yang tidak relevan dihapus. Jumlah kolom menjadi lebih sedikit dan hanya fitur yang dianggap berguna untuk modeling yang dipertahankan.

### 3.10 Mengecek Missing Value Setelah Cleaning

Setelah proses cleaning dan penghapusan kolom selesai, missing value dicek kembali. Missing value yang masih tersisa tidak langsung dihapus, karena akan ditangani menggunakan imputasi setelah train-test split.
"""

nan_cols_final = df.isnull().sum()
nan_cols_final = nan_cols_final[nan_cols_final > 0]
display(nan_cols_final.sort_values(ascending=False))

"""#### Interpretasi Output

Output menampilkan kolom yang masih memiliki NaN setelah cleaning final. NaN yang tersisa tidak langsung dihapus karena akan diisi menggunakan imputasi setelah data dibagi menjadi train dan test.

## 4. Modeling

Tahap modeling bertujuan membangun model machine learning yang mampu memprediksi `price` berdasarkan fitur kendaraan yang sudah diproses. Karena target berupa nilai numerik kontinu, pendekatan yang digunakan adalah regresi.

Pada tahap ini digunakan dua algoritma tree-based regression, yaitu Decision Tree Regressor dan Random Forest Regressor. Decision Tree merepresentasikan pendekatan pohon keputusan tunggal, sedangkan Random Forest merepresentasikan pendekatan ensemble yang menggabungkan banyak pohon keputusan.

Kedua model dilatih menggunakan data training yang sudah melalui proses imputasi dan encoding. Setelah itu, performanya dibandingkan menggunakan metrik evaluasi yang sama agar pemilihan model terbaik dilakukan secara objektif.

### 4.1 Memisahkan Fitur dan Target

Kolom `price` digunakan sebagai target karena nilai inilah yang ingin diprediksi. Kolom selain `price` digunakan sebagai fitur untuk membantu model mempelajari pola harga mobil bekas.
"""

X = df.drop("price", axis=1)
y = df["price"]

print(f"Jumlah data: {X.shape[0]:,}")
print(f"Jumlah fitur: {X.shape[1]}")

"""#### Interpretasi Output

Output menunjukkan jumlah data dan jumlah fitur setelah target `price` dipisahkan. Jumlah fitur inilah yang akan digunakan model untuk memprediksi harga mobil.

#### 4.1.1 Mengelompokkan Fitur Numerik dan Kategorikal

Kode ini memisahkan fitur berdasarkan tipe datanya. Pemisahan ini diperlukan karena fitur numerik dan kategorikal diproses dengan cara berbeda: numerik diimputasi dengan median, sedangkan kategorikal diimputasi dengan modus dan di-encoding.
"""

cat_cols = X.select_dtypes(include=["object"]).columns.tolist()
num_cols = X.select_dtypes(include=["number"]).columns.tolist()

print("Kolom numerik:")
print(num_cols)

print("\nKolom kategorikal:")
print(cat_cols)

"""#### Interpretasi Output

Output menampilkan daftar fitur numerik dan kategorikal. Daftar ini digunakan untuk menentukan perlakuan preprocessing yang berbeda antara kolom numerik dan kolom kategorikal.

### 4.2 Train-Test Split

Data dibagi menjadi data training dan testing sebelum imputasi dan encoding. Data training digunakan untuk melatih model, sedangkan data testing digunakan untuk mengevaluasi performa model pada data yang belum pernah dilihat.
"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"Jumlah data training: {X_train.shape[0]:,}")
print(f"Jumlah data testing: {X_test.shape[0]:,}")

"""#### Interpretasi Output

Output menampilkan jumlah data training dan testing. Pembagian ini memastikan bahwa model dilatih pada data training dan dievaluasi pada data testing yang belum dilihat saat training.

#### 4.2.1 Mengecek NaN pada Data Training

Kode ini mengecek missing value pada `X_train` sebelum imputasi. Tujuannya adalah menunjukkan kolom mana saja yang perlu diisi nilainya sebelum data digunakan untuk melatih model.
"""

missing_before_imputation = X_train.isnull().sum()
missing_before_imputation = missing_before_imputation[missing_before_imputation > 0]

display(missing_before_imputation.sort_values(ascending=False))

"""#### Interpretasi Output

Output ini menampilkan kolom pada data training yang masih memiliki missing value sebelum imputasi. Informasi ini membuktikan bahwa imputasi memang diperlukan sebelum model dilatih.

### 4.3 Imputasi Missing Value

Missing value diisi setelah data dibagi menjadi training dan testing. Kolom numerik diisi menggunakan median, sedangkan kolom kategorikal diisi menggunakan modus. Imputer di-fit hanya pada data training untuk mencegah data leakage.
"""

num_imputer = SimpleImputer(strategy="median")
cat_imputer = SimpleImputer(strategy="most_frequent")

X_train_imputed = X_train.copy()
X_test_imputed = X_test.copy()

X_train_imputed[num_cols] = num_imputer.fit_transform(X_train[num_cols])
X_test_imputed[num_cols] = num_imputer.transform(X_test[num_cols])

X_train_imputed[cat_cols] = cat_imputer.fit_transform(X_train[cat_cols])
X_test_imputed[cat_cols] = cat_imputer.transform(X_test[cat_cols])

missing_after_imputation = X_train_imputed.isnull().sum()
imputation_summary = pd.DataFrame({
    "missing_before": X_train.isnull().sum(),
    "missing_after": missing_after_imputation,
})

display(imputation_summary[imputation_summary["missing_before"] > 0])

"""#### Interpretasi Output

Tabel output menunjukkan jumlah missing value sebelum dan sesudah imputasi pada data training. Kolom `missing_after` bernilai 0 menandakan bahwa missing value berhasil ditangani dan data siap digunakan untuk modeling.

### 4.4 Model 1: Random Forest Regressor

Random Forest Regressor digunakan untuk merepresentasikan pendekatan ensemble berbasis banyak pohon keputusan. Secara arsitektur, model ini membangun beberapa Decision Tree dari subset data dan subset fitur yang berbeda, lalu menggabungkan hasil prediksi seluruh pohon sebagai prediksi akhir. Model ini digunakan untuk mengevaluasi apakah agregasi beberapa pohon keputusan dapat menghasilkan performa prediksi yang lebih baik dibandingkan pendekatan pohon tunggal.
"""

random_forest_preprocessor = ColumnTransformer(
    transformers=[
        ("num", "passthrough", num_cols),
        ("cat", OneHotEncoder(handle_unknown="ignore", sparse_output=False), cat_cols),
    ]
)

random_forest_model = Pipeline([
    ("preprocessor", random_forest_preprocessor),
    (
        "regressor",
        RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1),
    ),
])

random_forest_model.fit(X_train_imputed, y_train)

"""#### Interpretasi Output

Output cell ini menampilkan representasi pipeline Random Forest yang berhasil dibuat dan dilatih. Jika cell berjalan tanpa error, berarti model Random Forest sudah berhasil belajar dari data training.

### 4.5 Model 2: Decision Tree Regressor

Decision Tree Regressor digunakan sebagai model pembanding untuk merepresentasikan pendekatan pohon keputusan tunggal. Secara arsitektur, model ini membentuk struktur bercabang berdasarkan aturan pemisahan fitur yang paling informatif terhadap target. Pendekatan ini digunakan untuk membandingkan performa model tree based tunggal dengan model ensemble seperti Random Forest.
"""

decision_tree_preprocessor = ColumnTransformer(
    transformers=[
        ("num", "passthrough", num_cols),
        ("cat", OneHotEncoder(handle_unknown="ignore", sparse_output=False), cat_cols),
    ]
)

decision_tree_model = Pipeline([
    ("preprocessor", decision_tree_preprocessor),
    (
        "regressor",
        DecisionTreeRegressor(random_state=42),
    ),
])

decision_tree_model.fit(X_train_imputed, y_train)

"""#### Interpretasi Output

Output cell ini menampilkan representasi pipeline Decision Tree yang berhasil dibuat dan dilatih. Jika cell berjalan tanpa error, berarti model Decision Tree sudah siap digunakan untuk prediksi dan evaluasi.

## 5. Evaluation

Tahap evaluation digunakan untuk mengukur seberapa baik model memprediksi harga mobil pada data training dan data testing. Karena proyek ini merupakan masalah regresi, metrik yang digunakan adalah MAE, RMSE, dan R2.

MAE digunakan untuk melihat rata-rata selisih absolut antara harga aktual dan harga prediksi. RMSE digunakan untuk memberikan penalti lebih besar pada kesalahan prediksi yang tinggi. R2 digunakan untuk melihat seberapa besar variasi harga yang dapat dijelaskan oleh model.

Evaluasi dilakukan pada data test agar performa model dapat diukur pada data yang tidak digunakan saat training. Hasil evaluasi kedua model kemudian dibandingkan untuk menentukan model terbaik.

### 5.1 Evaluasi Random Forest

Pada tahap ini, model dievaluasi pada data training dan data testing. Perbandingan train dan test digunakan untuk melihat kemampuan generalisasi model, yaitu seberapa baik model mempertahankan performa pada data yang belum digunakan saat training.
"""

rf_train_pred = random_forest_model.predict(X_train_imputed)
rf_test_pred = random_forest_model.predict(X_test_imputed)

rf_train_rmse = np.sqrt(mean_squared_error(y_train, rf_train_pred))
rf_train_mae = mean_absolute_error(y_train, rf_train_pred)
rf_train_r2 = r2_score(y_train, rf_train_pred)

rf_test_rmse = np.sqrt(mean_squared_error(y_test, rf_test_pred))
rf_test_mae = mean_absolute_error(y_test, rf_test_pred)
rf_test_r2 = r2_score(y_test, rf_test_pred)

print("===== RANDOM FOREST - TRAIN =====")
print(f"RMSE : {rf_train_rmse:.2f}")
print(f"MAE  : {rf_train_mae:.2f}")
print(f"R2   : {rf_train_r2:.4f}")

print("\n===== RANDOM FOREST - TEST =====")
print(f"RMSE : {rf_test_rmse:.2f}")
print(f"MAE  : {rf_test_mae:.2f}")
print(f"R2   : {rf_test_r2:.4f}")

"""#### Interpretasi Output

Output evaluasi Random Forest menunjukkan nilai error dan R2 pada data training serta testing. Nilai test MAE sekitar 938.88 berarti rata-rata prediksi harga mobil meleset sekitar 938.88 dari harga aktual. Nilai test R2 sekitar 0.9049 menunjukkan model mampu menjelaskan sebagian besar variasi harga.

### 5.2 Evaluasi Decision Tree

Kode ini menghitung prediksi Decision Tree pada data training dan testing, lalu menghitung RMSE, MAE, dan R2. Hasilnya digunakan untuk membandingkan performa Decision Tree pada data training dan data testing secara terukur.
"""

dt_train_pred = decision_tree_model.predict(X_train_imputed)
dt_test_pred = decision_tree_model.predict(X_test_imputed)

dt_train_rmse = np.sqrt(mean_squared_error(y_train, dt_train_pred))
dt_train_mae = mean_absolute_error(y_train, dt_train_pred)
dt_train_r2 = r2_score(y_train, dt_train_pred)

dt_test_rmse = np.sqrt(mean_squared_error(y_test, dt_test_pred))
dt_test_mae = mean_absolute_error(y_test, dt_test_pred)
dt_test_r2 = r2_score(y_test, dt_test_pred)

print("===== DECISION TREE - TRAIN =====")
print(f"RMSE : {dt_train_rmse:.2f}")
print(f"MAE  : {dt_train_mae:.2f}")
print(f"R2   : {dt_train_r2:.4f}")

print("\n===== DECISION TREE - TEST =====")
print(f"RMSE : {dt_test_rmse:.2f}")
print(f"MAE  : {dt_test_mae:.2f}")
print(f"R2   : {dt_test_r2:.4f}")

"""#### Interpretasi Output

Output evaluasi Decision Tree menunjukkan performa model pada data training dan testing. Perbedaan nilai antara training dan testing menunjukkan seberapa konsisten performa model ketika digunakan pada data yang belum dilihat sebelumnya. Pada hasil ini, Decision Tree memiliki gap train-test yang lebih besar dibanding Random Forest.

### 5.3 Perbandingan Model

Hasil evaluasi Random Forest dan Decision Tree dirangkum ke dalam satu dataframe agar performa kedua model mudah dibandingkan. Model terbaik dipilih berdasarkan nilai `Test MAE` terkecil, dengan mempertimbangkan juga `Test RMSE` dan `Test R2`.
"""

model_comparison = pd.DataFrame({
    "Model": ["Random Forest", "Decision Tree"],
    "Train RMSE": [rf_train_rmse, dt_train_rmse],
    "Train MAE": [rf_train_mae, dt_train_mae],
    "Train R2": [rf_train_r2, dt_train_r2],
    "Test RMSE": [rf_test_rmse, dt_test_rmse],
    "Test MAE": [rf_test_mae, dt_test_mae],
    "Test R2": [rf_test_r2, dt_test_r2],
})

display(model_comparison)

best_model_name = model_comparison.loc[
    model_comparison["Test MAE"].idxmin(), "Model"
]

print(f"Model terbaik berdasarkan MAE pada data test adalah: {best_model_name}")

"""#### Interpretasi Output

Tabel perbandingan menunjukkan bahwa Random Forest memiliki performa test lebih baik dibanding Decision Tree. Hal ini terlihat dari nilai `Test MAE` dan `Test RMSE` yang lebih rendah serta `Test R2` yang lebih tinggi. Karena itu, Random Forest dipilih sebagai model terbaik.

### 5.4 Visualisasi Actual vs Predicted

Plot ini membandingkan harga aktual dengan harga prediksi untuk Random Forest dan Decision Tree. Garis merah menunjukkan prediksi ideal. Semakin dekat titik ke garis merah, semakin baik prediksi model.
"""

fig, axes = plt.subplots(1, 2, figsize=(14, 6), sharex=True, sharey=True)

plot_data = [
    (axes[0], rf_test_pred, "Random Forest"),
    (axes[1], dt_test_pred, "Decision Tree"),
]

min_price = y_test.min()
max_price = y_test.max()

for ax, prediction, title in plot_data:
    ax.scatter(y_test, prediction, alpha=0.3, s=10)
    ax.plot([min_price, max_price], [min_price, max_price], "r--", lw=2)
    ax.set_xlabel("Actual Price")
    ax.set_ylabel("Predicted Price")
    ax.set_title(f"Actual vs Predicted Price - {title}")

plt.tight_layout()
plt.show()

"""#### Interpretasi Output

Scatter plot menunjukkan seberapa dekat prediksi model dengan harga aktual. Titik yang dekat dengan garis merah berarti prediksi semakin baik. Sebaran titik yang cukup lebar menunjukkan masih ada error prediksi, terutama pada mobil dengan harga tinggi.

## 6. Kesimpulan

Berdasarkan hasil evaluasi, Random Forest Regressor dipilih sebagai model terbaik karena memiliki nilai MAE dan RMSE lebih rendah serta R2 lebih tinggi dibanding Decision Tree Regressor pada data test. Model ini mampu memprediksi harga mobil bekas dengan performa yang cukup baik, meskipun masih terdapat sebaran error terutama pada mobil dengan harga yang lebih tinggi.
"""

